version: '3'

volumes:
  db-data-postgres:
    driver: local

  db-data-postgres-config:
    driver: local

services:
  linda-postgres:
    image: postgres:9.6-bullseye
    container_name: linda-postgres
    environment:
      POSTGRES_DB: "linda-data"
      POSTGRES_USER: "linda-data"
      POSTGRES_PASSWORD: "linda-data"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - linda-net
    expose:
      - 5432
    volumes:
      - db-data-postgres-config:/var/lib/postgresql/dataConfig
      - db-data-postgres:/var/lib/postgresql/data

  linda:
    image: linda:0.1.0-beta.0
    container_name: linda
    networks:
      - linda-net
    ports:
      - "8080:8080"
    depends_on:
      - linda-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://linda-postgres:5432/linda-data

networks:
  linda-net:
    driver: bridge
